name: sklookie
channels:
  - defaults
dependencies:
  - python=3.11
  - langchain-core=0.3.25
  - langchain-openai=0.2.12
  - pydantic=2.7.4
  - pydantic_core=2.18.4
  - langchain-community=0.3.12
  - langgraph=0.2.59
  - streamlit=1.41.0
  - fastapi=0.115.4
  
